version: '3.8'

services:
  mysql:
    image: mariadb:11
    container_name: projetocnp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --innobd_buffer_pool_size=64M
      --max_connections=20
      --performance_schema=OFF
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetocnp_backend
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__MinhaConexao=${ConnectionStrings__MinhaConexao}
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: projetocnp_frontend
  #   ports:
  #     - "${FRONTEND_PORT}:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - NEXT_PUBLIC_API_URL= ${NEXT_PUBLIC_API_URL}
  #   restart: unless-stopped

volumes:
  mysql_data:

networks:
  default:
    name: projetocnp_network
